#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Thu Sep 25 16:46:51 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
import sys
import subprocess
# end wxGlade



class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        self.SetTitle("Python Compiler")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "Type or paste in path to python file (eg. /home/devel/python.py)")
        sizer_1.Add(label_6, 0, wx.EXPAND, 0)

        self.text_ctrl_4 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        sizer_1.Add(self.text_ctrl_4, 0, wx.EXPAND, 0)

        self.button_18 = wx.Button(self.panel_1, wx.ID_ANY, "OK")
        self.button_18.SetToolTip("Quit")
        sizer_1.Add(self.button_18, 0, 0, 0)

        self.button_17 = wx.Button(self.panel_1, wx.ID_ANY, "Cancel")
        self.button_17.SetToolTip("Quit")
        sizer_1.Add(self.button_17, 0, 0, 17)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.Bind(wx.EVT_TEXT, self.pass_path, self.text_ctrl_4)
        self.Bind(wx.EVT_TEXT_ENTER, self.run_pyinstaller, self.text_ctrl_4)
        self.Bind(wx.EVT_BUTTON, self.run_pyinstaller, self.button_18)
        self.Bind(wx.EVT_BUTTON, self.on_quit, self.button_17)
        # end wxGlade

    def pass_path(self, event):  # wxGlade: MyFrame.<event_handler>
        path = self.text_ctrl_4.GetValue()
        print(path)
        event.Skip()

    def on_quit(self, event):  # wxGlade: MyFrame.<event_handler>
        sys.exit()
        
    def run_pyinstaller(self, event):  # wxGlade: MyFrame.<event_handler>
        path = self.text_ctrl_4.GetValue()
        subprocess.run(["pyinstaller", path, "-F"])
        event.Skip()
# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
